title: Kinga Rapacka Portfolio
description: Kinga Rapacka Portfolio
theme: just-the-docs

url: https://github.com/KinRap/KinRap/KingaRapackaPortfolio/

aux_links:
  Template Repository: https://github.com/KinRap/KingaRapackaPortfolio




back_to_top: true
back_to_top_text: "Back to top"



footer_content: "Copyright &copy; 2024 KInga Rapacka. Distributed under the <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"